remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: Hong Junyang
description: M.S. in Data Science | B.E. in Computer Science
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
github:
  username: MrHong-J
