title: Hong Junyang
logo: /assets/img/logo.png
description: M.S. in Data Science | B.E. in Computer Science
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  username: MrHong-J
